### ISSUE TITLE
Unsecure Windows App

### ISSUE THREAD

**Issue by lexiconwriter** [erykjj/jwlmanager#1]
Hi, Windows 11 tells me the installation programm for jwlmanager is insecure. So it was stopped by the Microsoft Defender SmartScreen. The used asset was:

https://github.com/erykjj/jwlmanager/releases/download/v1.2.1/JWLManager_v1.2.1.exe

Any suggestions how to be sure the Defender is wrong?

**Comment by erykjj** [comment]
Thank you for reporting.

How to be sure the Defender is wrong? Well, have a look here. These are the virus scan results for the file your Defender blocked: https://www.virustotal.com/gui/file/31c427784446669f2e09055ce8c4c338b02d6edeb5b4a55308223b986d77ae7e/detection

You'll notice the great majority of anti-virus products report is as clean. In particular, notice the important/big players: Microsoft, Google, Avast, Kaspersky, McAfee, etc. So why do some report trojans and such? Well...

The app is basically a Python 3 script, and (for convenience) I use PyInstaller to package it up into a Windows executable. It's this process of packaging up a script that some over-zealous anti-virus products flag as dangerous, since the script _could be_ malicious.

So, if you prefer, you can install Python (and the required dependencies) and run the script directly. Other options include Virtualbox or [Sandboxie-Plus](https://sandboxie-plus.com/). But, of course, that's only if you don't trust me :-)

**Comment by erykjj** [comment]
@lexiconwriter , would you be willing to test a couple of "alternate" packages to see if they produce a similar alert from Windows Defender?

**Comment by lexiconwriter** [comment]
Hi Eryk,

thank you for the virus results. Funny that Microsoft alerts with one tool
but not with the other one.

If you need someone to test packages I can do it for u.

Kindly
Oliver

Am So., 18. Dez. 2022 um 01:58 Uhr schrieb Eryk J. ***@***.***

**Comment by erykjj** [comment]
Great. [Here](https://drive.filen.io/f/0224aac8-4a45-4b12-a9fb-9260a9d560e4#qejCh7cWNKdmTKsbk8kRmX1ZLm7oyb1m) you will find three Windows exe files - two stand-alone packages, and one in a zipped folder with the required dependencies.

Please tell me which of these trigger your Windows Defender alert.

Thank you!

**Comment by lexiconwriter** [comment]
Defender detects all of them. I guess because the publisher is unknown.

**Comment by erykjj** [comment]
That's a bit disappointing. Oh well, maybe down the road I'll try to find another method of packaging for Windows.

Thank you very much for testing!

**Comment by lexiconwriter** [comment]
Always welcome

**Comment by erykjj** [comment]
Question, @lexiconwriter : so does Defender not allow you to continue at all? Meaning, you cannot open the app because it's flagged as malware and you can't get past it? Or is it just a warning that you can ignore?

**Comment by lexiconwriter** [comment]
> Question, @lexiconwriter : so does Defender not allow you to continue at all? Meaning, you cannot open the app because it's flagged as malware and you can't get past it? Or is it just a warning that you can ignore?

Sorry for late reply: Defender gives a (martially) warning. But you will find a path to surround it in the dialog but not very explicit.

**Comment by erykjj** [comment]
Well, I'm glad to know it's possible to get around it. It appears a lot of developers are unhappy with this behavior by Windows Defender, forcing them to pay big money for a signed certificate.

**Comment by lexiconwriter** [comment]
Yes, not funny. Maybe it is possible to drop a comment on this Windows behaviour in your Readme. Your decision.

**Comment by erykjj** [comment]
Yes, thank you for the suggestion. I do mention it in a footnote.

**Comment by lexiconwriter** [comment]
I looked for the english defender text coming up when executing the installation file. Here it is under Windows 11:

![image](https://user-images.githubusercontent.com/5838099/210113609-ad36e772-c240-4c92-bc42-fc018ef70105.png)

In this case click on "More info". This will open this dialog:

![image](https://user-images.githubusercontent.com/5838099/210113787-91229f3a-1176-48ef-91c0-67d89aa56dc1.png)

For installation -> Run anyway

**Comment by erykjj** [comment]
Do you have to take these steps _every_ time you launch the app?

**Comment by lexiconwriter** [comment]
@erykjj No, it's only at installation time.

**Comment by erykjj** [comment]
By "installation" are you referring to unzipping the folder? Because it's not an _installer_ as such. It's either a stand-alone (complete) executable, or a zipped folder with the dependencies and executable.

I'd be happy if it only complained once (better still if it didn't complain at all :-))

**Comment by lexiconwriter** [comment]
I just used this linked exe: https://github.com/erykjj/jwlmanager/releases/download/v1.2.2/JWLManager_v1.2.2.exe It will be downloaded, the Windows downloader ask me to reject because is can be malicious, I tell "keep it" and then I doubleclick it in the download folder to start. Exe starts, and the defender comes up with the dialogs seen above.

**Comment by erykjj** [comment]
Right. That's the stand-alone package. So, if you double-click it again from the downloads folder, it just starts up without any nagging?

**Comment by lexiconwriter** [comment]
second time without nagging - true.

That is all the tool "everything" is finding on my Windows system:

![image](https://user-images.githubusercontent.com/5838099/210117303-f549fa64-6a06-4858-9990-fc50befe5a1c.png)

**Comment by erykjj** [comment]
The prefetch files are simply cached shortcuts...
But it's a relief to know it only complains once and can be bypassed. That makes the app usable if you trust the source.
Thank you very much for all your testing and reports!!! It will help anyone who comes across this in the future.

**Comment by erykjj** [comment]
Info added to [*SECURITY.md*](https://github.com/erykjj/jwlmanager/blob/master/.github/SECURITY.md)
