### ISSUE TITLE
Help sur JW Library

### ISSUE THREAD

**Issue by Samf973** [erykjj/jwlmanager#133]
Hello Erykjj

Thank you very much for your excellent work
I discovered your application less than a week ago and I'm thinking of using it.
I have a question for the connoisseur of the JW Library structure
I have nearly 4,000 categories that I create a la volte and which I used to come back to in order to modify them or group them together by changing the name. 
But since the version has playlists I can no longer change the names of the categories I've created.
I used to be able to do this from any publication but you have to go specifically to Individual Study.
Is this because I have too many categories? Or is everything I'm describing normal since the last version?
Thank you in advance for shedding some light on the subject.

Samf

**Comment by erykjj** [comment]
Hi @Samf973 ,
Thank you for reaching out. I'm trying to understand your issue...

What you are describing, you were able to do before but not anymore? Is that correct? If so, what version are you on now, and which was the last version where it worked?

Also, by categories, are you referring to tags? How were you changing the names? Using export and import and modifying the Excel?

**Comment by Samf973** [comment]
Hi Eryk

What I'm describing I could do before, yes. 

But it's the behaviour of JW Library that has changed. I haven't imported anything from JWLManager yet.

For example, before, when I was in a publication and I clicked on the tag of a note in that publication, I ended up in the Individual Study section and I could change the name of the tag directly. 

Today, if you're in the publication and you click on the tag, you stay in the publication even though all the corresponding tags are displayed, and you can't change the name of the tag. You have to go to the Individual Study section to access the "modified" button and here again it doesn't really work for me. 

Before, when you clicked on the tag name, the tag title changed and so did all the tags on the notes. Now when it works I only get the tag title changing and the tags in the notes keep their old names.   

Is it the same for you?

**Comment by erykjj** [comment]
OK, so this is not about JWLManager, but about JW Library since v14 (with playlists)...

This is where tags can be renamed (after selecting a note in a tag category):
![2023-12-21_09-10-35](https://github.com/erykjj/jwlmanager/assets/107011362/2b732ffd-ba65-4852-9864-9075701b9589)

My JWLManager app lets you export your notes (to Excel), retag them in bulk and re-import. I don't know what else I can suggest.

**Comment by Samf973** [comment]
Thank you for your response 
Indeed it is JW Library which is causing me a problem, the name changes are made only on the title of the category and not on the note and I thought you would have an explanation on this change in behavior compared to the previous versions.

**Comment by erykjj** [comment]
No, sorry, I have no access to their code, nor any input into the development.
