### ISSUE TITLE
Looking to contribute in any way I can.

### ISSUE THREAD

**Issue by 1-GB** [erykjj/jwlmanager#134]
I'm Mitch, a witness in Australia, learning Python.

Assuming everyone on the dev team for this project are witnesses from all over the place, I figured this was a good place to reach out to help in any way I can with this project, but mostly watch and take in more knowledge with how Python and this application works, as the best way to learn is experience.

Please reach out to me, if it's any easier, my discord is 1_gb

Hope all is well. Lots of people will find this tool useful.

Also I should probably point out that I haven't found any issues with the software, this is just the only way I could find to contact you guys.

**Comment by erykjj** [comment]
Hi Mitch,

Thanks for getting in touch.

First of all, I am the only developer on this project - and I'm far from being any kind of professional. I got into Python just over a couple of years ago, specifically for the purpose of developing this app, and it has been a learning experience all along - and still is.

Others have contributed - mostly with translations, testings, suggestions and recommendations; one even with some bug-fix code. Please feel free to contribute in any of those ways - it's all appreciated.

Eryk

**Comment by 1-GB** [comment]
Thanks, good to know.

I was more curious to know how you learnt Python as I have a few ideas up my sleeve that I want to develop later.

Is it a course? Self-taught with web resources? That sort of thing.

I know all of the basics, but can't really go much further.

**Comment by erykjj** [comment]
I had previously done some coding in Perl and Ruby. With Python, it was a learn-as-you-go by researching on the web what the project currently required, be it SQLite, Qt, compiling/packaging for other operating systems, etc. That's one reason why I chose to switch from Ruby to Python: the abundance of online examples and information, along with innumerable modules that one can use (some better than others). IMHO, Python is a very good general-purpose scripting language for that reason.
