### ISSUE TITLE
Screen size and resolution

### ISSUE THREAD

**Issue by erykjj** [erykjj/jwlmanager#153]
I have only one little case for your attention.
On my laptop I´m using  screen 1920 * 1080 and 150% scale (have a problems
with eyes, but don't think it´s rare case)
Cannot work with full list till change scale to 125% because screen size is
fixed and bottom strings are unavailable:

[image: image.png]
It`s really not a problem for me, but some users can get stuck.
Hope this bugreport helped.
:)

**Comment by erykjj** [comment]
@korotkiyYurii please reupload the screenshot image. Thank you for reporting.

**Comment by korotkiyYurii** [comment]
![2024-01-13_22h58_02](https://github.com/erykjj/jwlmanager/assets/55229171/0007d903-48a0-47ab-a145-99418b728993)
![2024-01-13_22h58_02](https://github.com/erykjj/jwlmanager/assets/55229171/75ad35ea-6565-4416-aabf-79f0edb0e06c)

**Comment by korotkiyYurii** [comment]
when application is running first time a session, it cannot be operated, as menus a hidden above as well
![2024-01-14_10h42_25](https://github.com/erykjj/jwlmanager/assets/55229171/8ad0c6f9-fe52-47f4-a9c5-66a1ef6c81dc)

**Comment by korotkiyYurii** [comment]
Need to delete Config file near exe, because despite screen scale is changed to 125 % after first start, menus are still hidden in 125% or 100%
So the only way is to start using 125% scaling.

**Comment by korotkiyYurii** [comment]
Also a final little 3 interface changes added due to deeper look on functionality (RUS and UKR)

**Comment by erykjj** [comment]
I understand. Yes, this can be a problem. I will address this.

Thank you for bringing this up and for your continued support with translation improvements!!

**Comment by erykjj** [comment]
@korotkiyYurii 
Please test this release and let me know if it behaves acceptably.
Thank you.

[v4.3.2-TESTING](https://github.com/erykjj/jwlmanager/releases/tag/v4.3.2-TESTING)

**Comment by korotkiyYurii** [comment]
v.4.3.2 Tested Ok with all scales: 100%...150% no interface issues.
