### ISSUE TITLE
App crashing when I attempt to "view" my notes

### ISSUE THREAD

**Issue by Hizkiah** [erykjj/jwlmanager#158]
When I attempt to view a note this happens:
![image](https://github.com/erykjj/jwlmanager/assets/157563609/de7bb933-e2f1-420b-befa-0d1d10177aac)

**Comment by erykjj** [comment]
Hi @Hizkiah 

Thank you very much for reporting this. It appears one of your notes has an empty (NULL) content field. Very good catch!

Please try [v4.3.3-TESTING](https://github.com/erykjj/jwlmanager/releases/tag/v4.3.3-TESTING) and let me know ASAP if it works correctly now.

**Comment by erykjj** [comment]
Should be fixed in v4.3.3
