### ISSUE TITLE
Exporting to excel error

### ISSUE THREAD

**Issue by jonharrell** [erykjj/jwlmanager#159]
JWLManager v4.3.3
Windows-10-10.0.22631-SP0

Traceback (most recent call last):
  File "JWLManager.py", line 1125, in export_items
  File "JWLManager.py", line 1065, in export_notes
  File "JWLManager.py", line 1011, in get_notes
sqlite3.OperationalError: no such column: n.Created

**Comment by erykjj** [comment]
Hi,
Thank you for reporting. I'll have a look.

Are you exporting from a .jwlibrary archive created with the the latest version of JW Library, or an older version?

**Comment by jonharrell** [comment]
It was with the latest version. I was trying to merge two files and wanted to get a clean export of both to manually work through them

**Comment by jonharrell** [comment]
reindexing gave this error:

JWLManager v4.3.3
Windows-10-10.0.22631-SP0

Traceback (most recent call last):
  File "JWLManager.py", line 2374, in trim_db
sqlite3.OperationalError: no such table: PlaylistItemLocationMap

**Comment by jonharrell** [comment]
I'm sorry I think I was including a sign language back up as well...

**Comment by erykjj** [comment]
It almost looks like you've got an old schema version (older JW Library)....

Please check the JW Library version for me (should be v14+)

Also, if you can, save both archives using that v14+. You may have to restore them (restore a backup) and save them again from JW Library.

**Comment by erykjj** [comment]
🤔
I'm not familiar with those... It's that through JW Library as well?

Does everything work correctly otherwise?

**Comment by jonharrell** [comment]
It is the JW library sign app. I have both of them backing up into the same folder and grabed one of the sign versions. They have play lists etc but came out with features a few years prior to the main app so I'm sure the db is different.

**Comment by erykjj** [comment]
Just to make sure I understand: you are opening a certain .jwlibrary archive (from the JW Library app) and...
1) you _can_ **export to Excel** without issues
2) **importing** that same **Excel** file _crashes_
3) **exporting to text** also _crashes_
Is that correct?

Is there any way you can send me that .jwlibrary archive? You can use the Mask option from Utilities menu to obfuscate all your text fields and then save this archive, zip it up and attach, please. I will have to have a look at the database itself.

**Comment by jonharrell** [comment]
Correct, export to xls works, import errors and export to txt errors. 
[masked-exportfromdesktop_2024-02-09.zip](https://github.com/erykjj/jwlmanager/files/14226530/masked-exportfromdesktop_2024-02-09.zip)

**Comment by erykjj** [comment]
OK, I think you found what I would call an "edge case" involving adding a note to a document (publication page) from the app menu ("Add Note"), which doesn't associate the note with any paragraph (block) in particular.

I was handling this with the Bible notes, but not with "regular" publications. I will push out a fix in the next day or two.

**Comment by erykjj** [comment]
@jonharrell 
Your archive contains at least one messed-up note: NoteId 221.
It's attached to 2 Corinthians 11:53 in the nwt. That verse doesn't exist. JW Library will show it in the notes section, but try clicking the link at the bottom of it...

That aside, the issue you reported is also present. Fix if coming.

**Comment by erykjj** [comment]
@jonharrell please try [v4.4.0](https://github.com/erykjj/jwlmanager/releases/tag/v4.4.0) and let me know how it behaves. I did some testing and it behaves correctly, but please do keep backups till you're sure it's all good.

Also, do you think it would it be helpful to have access to JW Sign backups in JWLManager? If so, send me a sample backup file and I'll see if I can make some adaptations.

**Comment by jonharrell** [comment]
The updated version works great. 

Also, attached is a jwlib file for sign language with a playlist added for a talk
[masked-exportfromdesktop_2024-02-09.zip](https://github.com/erykjj/jwlmanager/files/14239927/masked-exportfromdesktop_2024-02-09.zip)
. Please let me know if you would like anything specific - db files etc.

**Comment by jonharrell** [comment]
Jw sign single playlist exports and merging would be incredibly helpful.
I've also manually edited the database a few times to work past crashes
caused by directories that changed after upgrading a computer.



Jon Harrell

**Comment by erykjj** [comment]
> Also, attached is a jwlib file for sign language with a playlist added for a talk
> [masked-exportfromdesktop_2024-02-09.zip](https://github.com/erykjj/jwlmanager/files/14239927/masked-exportfromdesktop_2024-02-09.zip)

Are you sure you attached the correct file?

**Comment by erykjj** [comment]
> Jw sign single playlist exports and merging would be incredibly helpful.

Do you mean being able to select individual items in the Playlists view and exporting/importing them (like with Notes, etc.)?

**Comment by jonharrell** [comment]
It would be very helpful to be able to export individual playlists and
import them. Also, basic editing of the publication lists would help with
issues that arise from changing drive letters. In the past, after upgrading
computers I've manually edited the db files to point to the media files'
new locations.

But in general the db is a lot less used from the user standpoint as notes
do not exist and only playlists.

The playlist feature predates the main JW library by several years (around
2015/6) so I would suspect it could be very different in structure.

Jon Harrell

**Comment by erykjj** [comment]
I can certainly think about it...
Please resend the backup file generated by the JW Sign app.

**Comment by jonharrell** [comment]
[UserdataBackup_2024-02-13_HPBIGBROTHER.zip](https://github.com/erykjj/jwlmanager/files/14258033/UserdataBackup_2024-02-13_HPBIGBROTHER.zip)

Sorry about that, the last attachment was obviously wrong and the actual one was too large. I simplified the talk by removing many of the videos and it is small enough now.

**Comment by erykjj** [comment]
Thank you.
I will have a look and think about it.

I will close this issue as completed, if you don't mind.

**Comment by erykjj** [comment]
@jonharrell 
Please give your input: https://github.com/erykjj/jwlmanager/discussions/166

**Comment by erykjj** [comment]
> It would be very helpful to be able to export individual playlists and import them. Also, basic editing of the publication lists would help with issues that arise from changing drive letters. In the past, after upgrading computers I've manually edited the db files to point to the media files' new locations. But in general the db is a lot less used from the user standpoint as notes do not exist and only playlists. The playlist feature predates the main JW library by several years (around 2015/6) so I would suspect it could be very different in structure. Jon Harrell

Hi @jonharrell 
I have been doing a bit of work on the playlist export/import. For now, I've got the export working (?). I need someone to do testing. Are you up for it?

If so, what kind of OS do you use? Can you by any chance execute the Python directly, or do you need the compiled binaries?
