### ISSUE TITLE
when select "Highlights" in Polish

### ISSUE THREAD

**Issue by xKamil01** [erykjj/jwlmanager#172]
When opening underscores

JWLManager v4.5.0
Windows-10-10.0.19045-SP0

Traceback (most recent call last):
  File "JWLManager.py", line 696, in regroup
  File "JWLManager.py", line 666, in build_tree
TypeError: list indices must be integers or slices, not str

**Comment by erykjj** [comment]
Thank you for reporting @xKamil01 

I don't understand "When opening underscores".

Also, does this happen just with Highlights in Polish? Other languages (same archive) work OK?

**Comment by erykjj** [comment]
I was able to reproduce this. It has to do with the translation files. Will fix.

**Comment by xKamil01** [comment]
English language work OK, bugs on Polish

**Comment by xKamil01** [comment]
Do you need so many languages? This creates problems

**Comment by erykjj** [comment]
> Do you need so many languages? This creates problems

It's not that I "need" them; I mostly use English. But it's nice to have an app in your own language, no?

Yes, it does make it a bit more challenging, but now I know exactly what causes the issues and it's generally easy to fix - thanks to reports such as yours... Very much appreciated!!

Fix will be implemented in v4.5.1.
