### ISSUE TITLE
Export playlist in English lang

### ISSUE THREAD

**Issue by xKamil01** [erykjj/jwlmanager#173]
JWLManager v4.5.0
Windows-10-10.0.19045-SP0

Traceback (most recent call last):
  File "JWLManager.py", line 1215, in export_items
  File "JWLManager.py", line 1165, in export_playlist
  File "JWLManager.py", line 1146, in playlist_export
sqlite3.OperationalError: no such column: None

**Comment by erykjj** [comment]
@xKamil01 
Would you be able to tell me more: how many items were you exporting? What kinds of items? Is it one particular item that fails?
Any chance you can send me a copy of the archive? You can delete everything else (notes, hightlights, etc.), just leave the playlists.

**Comment by xKamil01** [comment]
[https://sharemods.com/mgq069af7b7y/MODIFIED.zip.html](url)

**Comment by erykjj** [comment]
Have ALL these items been added the usual way (through JW Library)?
In particular, you have items like these in your database:
- Muza 1.mp3
- Muzyka 2.mp3
- Muzyka 3.mp3
Where do these come from?

**Comment by erykjj** [comment]
@xKamil01 
Please try this test version: https://drive.filen.io/d/e7fb944d-e072-40fa-940e-1cca894b5157#TUmbcOaCvQKa9vdp9OTXYhjBwf2cSoFa

and let me know if your issues are resolved.

Thank you!

**Comment by erykjj** [comment]
Fix with 9f21bedd0d9434f5accdd19f335dc80bf3dc6eca

**Comment by xKamil01** [comment]
these files were imported into JW Library from a memory card. You can even import regular songs into the application.

I will test the new version when it's a day in Poland  😆
