### ISSUE TITLE
JWLManager 4.5.0 don't start in macOS 12

### ISSUE THREAD

**Issue by stecchio66** [erykjj/jwlmanager#174]
The latest release don't start.
The warning message at launch is: You can't open "JWLManager.app" because it is not supported on Mac".
My macOs version is Monterey 12.7.5

Thanks
Stefano
<img width="292" alt="2024-05-31_13-52-32" src="https://github.com/erykjj/jwlmanager/assets/118082203/882e7ec6-13b7-4862-b51e-bad6812885dd">

**Comment by erykjj** [comment]
Hi @stecchio66 

Thank you for reporting.

I use Github runners (virtual systems) to build the different OS binaries. As per https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners/about-github-hosted-runners : 
- The `macos-11` label has been deprecated and will no longer be available after 6/28/2024
- The `macos-latest` label (which I used) currently uses the macOS 14 runner image

I don't know much about Macs. Is upgrading from 12 to 14 a big/complicated/expensive issue? If it is, I suppose I could build with `macos-11` for another month, but not after that :-(

**Comment by erykjj** [comment]
The other option would be to install Python (3.11 or higher) on your system (along with the required dependencies).

**Comment by stecchio66** [comment]
Thanks @erykjj 

I cannot update to macos 14because my iMac doesn't support it.
But is not a problem. For now i continue with 4.4.1 release.

Thank you again.
Stefano

**Comment by erykjj** [comment]
I will build with `macos-11` until no longer possible.

**Comment by erykjj** [comment]
@stecchio66 
Please test this and let me know if it starts up OK
https://drive.filen.io/d/117e9cec-aa9b-4282-a78f-918bdc86d022#g7CldniM9iaGJjnFgeLWmHDxK1jQO5aZ

**Comment by stecchio66** [comment]
@erykjj 

> Please test this and let me know if it starts up OK
https://drive.filen.io/d/117e9cec-aa9b-4282-a78f-918bdc86d022#g7CldniM9iaGJjnFgeLWmHDxK1jQO5aZ

It starts
