### ISSUE TITLE
4.5.1 Issue with importing annotation file

### ISSUE THREAD

**Issue by jonharrell** [erykjj/jwlmanager#176]
I am trying to merge files from three sources one contains annotations from my laptop and it does not like this line:
Error on import! Faulting entry: #91

Entry 91:
mwb	20240300	202024081	tt21	

It seems that if the annotation is blank then the error pops up. If I insert a single space the error goes away.

**Comment by erykjj** [comment]
Thank you very much for your report, @jonharrell !!

Good catch!
