### ISSUE TITLE
Sharing annotations with iOS devices

### ISSUE THREAD

**Issue by cienypico** [erykjj/jwlmanager#177]
Thank you for this programme. I have a number of annotations in various publications in JWLibrary on my Windows 11 laptop. However, there are annotations in one publication in particular that I would like to share with my iPad and iPhone without sharing other annotations in other publications - I hope that makes sense - is there a way I can do this without going through the process of merging backups across the devices? Thank you.

**Comment by erykjj** [comment]
Hi @cienypico 

If I understand correctly, the issure here is with the (current) JW Library app: on import, it does not _add_ to the current user data ("merge"), but _replaces_ the entire database with another. So, no, there is (at present) no way to import just a few items (of any kind).

That's why JWLManager exists :-) You are probably already doing it this way, but for the sake of others:

1. Open the backup archive from the laptop
2. Select (check) just the items you want to transfer
3. Export them
4. Open the backup from the iDevice
5. Import the items you just exported
6. Save this new archive and import it into JW Library on the iDevice

Doing it this way gives you fine-grained control on what is merged (which is what you and I want), plus the ability to clean-up some "clutter" that has accumulated over the years :-)

**Comment by cienypico** [comment]
Thank you for taking the time to reply - I will try your suggestions - however I note that when I export the annotations it saves the file as an Excel file - I am not sure how to import that into the JWLibrary on my iPad/ iPhone.....is there something I am missing?

**Comment by erykjj** [comment]
> Thank you for taking the time to reply - I will try your suggestions - however I note that when I export the annotations it saves the file as an Excel file - I am not sure how to import that into the JWLibrary on my iPad/ iPhone.....is there something I am missing?

Hmm, it looks like you are skipping steps 4 to 6 :-)
Once you export into an Excel file, open the backup from JW Library on your iPad/iPhone in JWLManagar. Import that Excel file and save this updated archive with a new name. Then restore this new archive on your iPad/iPhone.

**Comment by cienypico** [comment]
> > Thank you for taking the time to reply - I will try your suggestions - however I note that when I export the annotations it saves the file as an Excel file - I am not sure how to import that into the JWLibrary on my iPad/ iPhone.....is there something I am missing?
> 
> Hmm, it looks like you are skipping steps 4 to 6 :-) Once you export into an Excel file, open the backup from JW Library on your iPad/iPhone in JWLManagar. Import that Excel file and save this updated archive with a new name. Then restore this new archive on your iPad/iPhone.

Thank you, again, for your patience. the penny dropped and therein lies the lesson - always follow the instructions.

**Comment by cienypico** [comment]
> > Thank you for taking the time to reply - I will try your suggestions - however I note that when I export the annotations it saves the file as an Excel file - I am not sure how to import that into the JWLibrary on my iPad/ iPhone.....is there something I am missing?
> 
> Hmm, it looks like you are skipping steps 4 to 6 :-) Once you export into an Excel file, open the backup from JW Library on your iPad/iPhone in JWLManagar. Import that Excel file and save this updated archive with a new name. Then restore this new archive on your iPad/iPhone.


Thank you, again, for your patience. the penny dropped and therein lies the lesson - always follow the instructions.

**Comment by erykjj** [comment]
Does that mean it worked for you?

**Comment by cienypico** [comment]
I am going to try it later today / tomorrow- busy day Following your instructions it should do so but will let you know - thank you, againSent from my iPhoneOn 16 Jun 2024, at 08:20, Eryk J. ***@***.***> wrote:﻿
Does that mean it worked for you?

**Comment by cienypico** [comment]
Worked perfectly for me, thank you.

I was able to share annotations and notes in one publication only from my
laptop to my iPad and also retain my notes etc that were on my iPad

Thank you for sharing this and for your hard work in preparing it

And thank you, again, for your patience!

**Comment by cienypico** [comment]
Just one query and it is probably asking too much - is it possible to share
only one jwpub publication that includes annotations and notes with someone
else without messing up their JWLibrary - I hope that makes sense

Thank you

**Comment by erykjj** [comment]
As I mentioned before, JW Library (at present) replaces one database with another when you restore, so either you or the other person would have to do what you did with your own archives: use JWLManager to export/import.

If the other person knows how to use JWLManager, you could simply export the notes and annotations and send them those two files to import into their own archive (using JWLManager). Or, they send you their JW Library backup archive and you import and send them back the resulting archive to restore into JW Library.

I hope that helps ;-)

**Comment by cienypico** [comment]
Thank you for your replyI thought that might be the case but thought I would ask anyway Your hard work and ingenuity is appreciated Sent from my iPhoneOn 17 Jun 2024, at 19:43, Eryk J. ***@***.***> wrote:﻿
As I mentioned before, JW Library (at present) replaces one database with another when you restore, so either you or the other person would have to do what you did with your own archives: use JWLManager to export/import.
If the other person knows how to use JWLManager, you could simply export the notes and annotations and send them those two files to import into their own archive (using JWLManager). Or, they send you their JW Library backup archive and you import and send them back the resulting archive to restore into JW Library.
I hope that helps ;-)
