### ISSUE TITLE
Merging archives

### ISSUE THREAD

**Issue by Samf973** [erykjj/jwlmanager#178]
Hello Eryk

Thank you very much for your excellent work. I would like to understand how to use jwlmanager to merge jwlibrary archives.

Samuel

**Comment by erykjj** [comment]
Hi @Samf973 ,

Before I write a long explanation, have you looked at the instructions on how to [Export](https://github.com/erykjj/jwlmanager/blob/master/res/HELP.md#export) and [Import](https://github.com/erykjj/jwlmanager/blob/master/res/HELP.md#import)?

Is there something in there that I need to clarify?

Basically...
1. Open one backup archive in JWLManager
2. Select (check) just the items you want to transfer
3. Export them
4. Open the other backup archive in JWLManager
5. Import the items you just exported
6. Save this new archive and import it into JW Library

**Comment by erykjj** [comment]
Hi @Samf973 

Were you able to accomplish your merge?

**Comment by Samf973** [comment]
Bonjour

No, I didn't understand how to do it

Samuel

De : Eryk J. ***@***.***>
Envoyé : lundi 12 août 2024 09:47
À : erykjj/jwlmanager ***@***.***>
Cc : Samf973 ***@***.***>; Mention ***@***.***>
Objet : Re: [erykjj/jwlmanager] Fusion (Issue #178)


Hi @Samf973<https://github.com/Samf973>

Were you able to accomplish your merge?

-

**Comment by erykjj** [comment]
Hi Samuel,

I would like to help you, but just saying you did't understand is too general. How far do you get? What have you done? Where do you have trouble? If you tell me what you do, I can tell you what step(s) you may be missing ;-)

It works, I assure you :-)

Eryk

**Comment by Samf973** [comment]
Hello

I tried this and got this error message

JWLManager v4.3.0
Windows-10-10.0.22631-SP0

Traceback (most recent call last):
  File "JWLManager.py", line 1126, in export_items
  File "JWLManager.py", line 1066, in export_notes
  File "JWLManager.py", line 1058, in get_notes
KeyError: None

Samuel
De : Eryk J. ***@***.***>
Envoyé : lundi 12 août 2024 17:54
À : erykjj/jwlmanager ***@***.***>
Cc : Samf973 ***@***.***>; Mention ***@***.***>
Objet : Re: [erykjj/jwlmanager] Fusion (Issue #178)


Hi Samuel,

I would like to help you, but just saying you did't understand is too general. How far do you get? What have you done? Where do you have trouble? If you tell me what you do, I can tell you what step(s) you may be missing ;-)

It works, I assure you :-)

Eryk

-

**Comment by erykjj** [comment]
Hi @Samf973 

Is it working for you?

**Comment by erykjj** [comment]
> I have an anti-virus that detects the software as a threat and won't let me install it.

Please see this: https://github.com/erykjj/jwlmanager?tab=security-ov-file#readme

**Comment by Samf973** [comment]
Bonjour

I'm sorry, but it doesn't work for me and my anti-virus keeps quarantining the software.

SF
De : Eryk J. ***@***.***>
Envoyé : lundi 9 septembre 2024 21:33
À : erykjj/jwlmanager ***@***.***>
Cc : Samf973 ***@***.***>; Mention ***@***.***>
Objet : Re: [erykjj/jwlmanager] Merging archives (Issue #178)


Closed #178<https://github.com/erykjj/jwlmanager/issues/178> as completed.

-

**Comment by erykjj** [comment]
Did you see the link I sent pointed you to? There is a workaround. I can't help you if all you say is that it doesn't work.
