### ISSUE TITLE
Exporting notes to markdown

### ISSUE THREAD

**Issue by serhiyjwbook** [erykjj/jwlmanager#180]
Good day
Is it possible to add the function of exporting notes to markdown format to the program? Ideally - in a form compatible with Obsidian.md so that there is a separate note for each article: "Name of the article or section" "metadata of the publication" "highlights and comments" with the preservation of the color scheme?

**Comment by erykjj** [comment]
In the mean time, there is an option there already in the Note Viewer to export to text. I could easily modify the format of the meta-data section.

![2024-10-03_07-25-53](https://github.com/user-attachments/assets/eccfccca-fa30-45cf-8dfd-1287f41a6f35)
![2024-10-03_07-26-42](https://github.com/user-attachments/assets/aab2e019-4cdd-4492-9cf2-688d57604e15)

My big concern would be if you wanted to export a large number of notes, each one to a separate file, which might create a huge number of files.

**Comment by serhiyjwbook** [comment]
> Мене дуже хвилює, якщо ви хочете експортувати велику кількість нотаток, кожну в окремий файл, що може створити величезну кількість файлів.

No, I want selections and notes from one publication - article or book - to be stored in one .md file. Ideally, while preserving the color scheme of selections and tags.
Approximate structure of the note file:
Title of the article
metadata
Highlights and notes

"highlight" in color or with a text color designation
"note"
tag in a format that can be recognized by Obsidian.md


I am very far from programming, but I am interested in developing a knowledge management system for Bible studies. Something like Zettelkasten. The exported from JWL note will be used as a literary note. The notes will be made into "atomic notes" with key ideas.

My email is serhiyafanasyev@gmail.com, Telegram is @Sergjw

**Comment by erykjj** [comment]
I sent you an email; check your spam ;-)

**Comment by erykjj** [comment]
Any thoughts/observations on the proposed solution, @SchneiderSam & @serhiyjwbook ?

**Comment by SchneiderSam** [comment]
@erykjj Please excuse the late reply. I had not yet tried to test this. As soon as I have a little more time and quiet I will try it. Have you ever used Obsidian?

**Comment by erykjj** [comment]
Yes, I do use Obsidian.

I'll await your analysis :-)

**Comment by didpeugeot** [comment]
Hey sorry to add a grain of salt. 

Also interested in markdown export. But I would like to have 1 file per note. Huge # of files but VERY useful for my personal study. Could that be an option?

**Comment by erykjj** [comment]
Hi @didpeugeot 

Thank you for your input. I will consider it ;-)

**Comment by erykjj** [comment]
So, one question arises: how should the separate files be named? Some notes can have exactly the same title, so if I use that, it would over-write the previous. On the other hand, some titles can be quite long...

I could use the note's GUID to create filenames something like this: _5dacbb2e-6575-11ee-9e09-ccd9ac8e792a.md_ But this make it harder to identify the notes in the file manager.

Thoughts/suggestions?

**Comment by erykjj** [comment]
OK. I decided I will go with the GUID naming. The file-save dialog will ask for a _directory_ where the individual files will be saved (over-writing and previous ones that may be in there with the same name).

**Comment by erykjj** [comment]
Please test v[5](https://github.com/erykjj/jwlmanager/releases/tag/v5.0.0)

**Comment by didpeugeot** [comment]
You're super fast! It's great to have you in our life! 😊 So, file-save dialog asking for directory works. But not file separation. Nor Markdown. I have tested v5 and all notes do get exported in 1 super LONG text file. My suggestion: 

1. Split books into folders.
2. Then split folders into chapters.
3. In each folder, split each note into an individual file with file name just reflecting the 1st few words of the note. 

This way, we can identify the notes either in the file manager or by way of comparison with JWL. Something like this.

![CleanShot 2024-10-19 at 06 09 06@2x](https://github.com/user-attachments/assets/cedf7705-ac6a-48b2-b40a-1d5c27d11ce8)

Being able to export into Markdown would be a game changer to import directly into Obsidian or similar software (Joplin, Capacities, Anytype, Crafts, Reflect...)

**Comment by erykjj** [comment]
Hey @didpeugeot 

Please try again with the same version you have. But keep in mind this markdown export is _not_ via the EXPORT button on the main interface. You select your notes then choose VIEW to see them (and filter if you wish) in the Data Viewer. Then click the MD button there.

![2024-10-19_07-17-03](https://github.com/user-attachments/assets/bb3c9460-03ab-4b36-9939-1788cffa2942)

**Comment by erykjj** [comment]
Not all notes have chapters - only Bible ones do. Also, many note titles would be similar an would over-write.

I will leave it up to each one to handle (sort/rename) the saved notes. That way, each one can write their own "adapter".

But I may take up your suggestion in the future :-)

**Comment by didpeugeot** [comment]
Thank you! MD View -> Save does work well. 

2 ideas for input:

1. Markdown preview does not open all my notes (over 1.2K)... What is the limit # of files that can be previewed?
2. The purpose of automating JWL Study notes export is not to go through the manual process of renaming and recategorizing a large # of notes. Without folder by book / chapter, it becomes very hard to identify Bible study notes and to transfer them gradually over to Obsidian. Hmmm... Could saving this way be optional (for those wanting to export study notes from Bible)? 🤔

Very grateful for your very clear software, instructions, and all your hard work behind the scene!!!! 😊

**Comment by erykjj** [comment]
> 1. Markdown preview does not open all my notes (over 1.2K)... What is the limit # of files that can be previewed?

Right now I have it at 1,500 because it takes quite long to build the preview if you view too many at a time.

**Comment by erykjj** [comment]
> 2\. The purpose of automating JWL Study notes export is not to go through the manual process of renaming and recategorizing a large # of notes. Without folder by book / chapter, it becomes very hard to identify Bible study notes and to transfer them gradually over to Obsidian. Hmmm... Could saving this way be optional (for those wanting to export study notes from Bible)? 🤔

I understand. I have already implemented the categorization into a sub-directory tree like you mentioned earlier.

I just have to decide on the final filename for each note, whether to leave is a GUID or an abbreviated note title...

**Comment by erykjj** [comment]
> Very grateful for your very clear software, instructions, and all your hard work behind the scene!!!!

Thank you for your input. Not everone uses/needs the same functionality, so it's nice to get feedback from users ;-)

**Comment by didpeugeot** [comment]
It would make sense to categorize according to position in source document (whether that is the Bible / Insight / etc...) 

JWL keeps track of that. For the Bible, files would show up in order (Gen 1:1, 1:2 vs... Gen 5:10; 41:14; 3:15....)

![CleanShot 2024-10-19 at 21 06 14@2x](https://github.com/user-attachments/assets/b59fa0b6-ab02-4ee4-885f-4a72ea9f883d)

**Comment by erykjj** [comment]
It'll will be along those lines in the next release.

**Comment by erykjj** [comment]
@serhiyjwbook @SchneiderSam @didpeugeot 

Please test and report if you can ;-)
[v5.1.0-RC](https://github.com/erykjj/jwlmanager/releases/tag/v5.1.0-RC)

**Comment by erykjj** [comment]
Export to markdown via EXPORT button

**Comment by didpeugeot** [comment]
App crashed. I got this:

JWLManager v5.1.0
macOS-15.0.1-x86_64-i386-64bit

Traceback (most recent call last):
  File "JWLManager.py", line 1334, in export_items
  File "JWLManager.py", line 1204, in export_notes
  File "JWLManager.py", line 924, in shorten_title
AttributeError: 'NoneType' object has no attribute 'group'

____

Wondering also if 1.5K files limit can be removed as it means exporting notes by smaller batch + create 1 folder per book vs 1 export for all. 🤓

**Comment by erykjj** [comment]
Thank you for reporting @didpeugeot 
I have addressed that issue.

Please try [v5.1.0-RC2](https://github.com/erykjj/jwlmanager/releases/tag/v5.1.0-RC2)

As to the limit, that only applies to the Data Viewer. Since markdown export has been moved to the main interface EXPORT button, there is no more limit; you can export all your notes at once (or only selected ones). And they should be organized in a folder-tree.

**Comment by didpeugeot** [comment]
It worked!!! 🙌🙌🙌🙌

Thank you so much!

**Comment by erykjj** [comment]
Any suggestions/observations?

**Comment by glenmwright** [comment]
Good morning, 

I ran into a crash with RC2. I expect it is due to invalid characters in my Titles. 

JWLManager v5.1.0
Windows-10-10.0.19045-SP0

Traceback (most recent call last):
  File "JWLManager.py", line 1336, in export_items
  File "JWLManager.py", line 1224, in export_notes
OSError: [Errno 22] Invalid argument: 'C:\\MarkdownFiles/nwtsty-E/42_Luke/008/015_Robert Luccioni: Be […] 8:15)_308b65e8.md'

The full title of the note is "Robert Luccioni: Be Determined to Endure (Luke 8:15)"

It looks like this was the 3rd export and they did not export the note. 
![image](https://github.com/user-attachments/assets/1cdc56c5-4ad5-4107-b3e1-70449b7087de)

**Comment by glenmwright** [comment]
As a test, I removed all the colon (:) characters from my note titles. That allowed the Export to Markdown to complete without error/crashing. However, while it created a file for each of my notes, there is no content inside the note and the file does not have the .md file extension.

**Comment by erykjj** [comment]
Hi @glenmwright 

Once again, thank you for testing and reporting! It's good to have someone on Windows :-)

Do any of the exported notes come out correctly (name, extension, content)?

**Comment by glenmwright** [comment]
Yes, there was one file out of 333 that exported correctly. That helped me find the problem, it was still the colon character that was in the title within a scripture quote, for example (Gen. 1**:**1). Replacing all the colons with a dash/hyphen resolved it.

**Comment by erykjj** [comment]
OK. Please test again with [RC3](https://github.com/erykjj/jwlmanager/releases/edit/untagged-77994597fc4be18eb954) - it should handle the colons in the filenames correctly.

**Comment by glenmwright** [comment]
That fixed it for this Windows user 😆

**Comment by glenmwright** [comment]
Good day, 

I am getting an error with version 5.1.0 when importing both in plain text and Excel. The same import files import successfully in version 5.0.0. 

JWLManager v5.1.0
Windows-10-10.0.19045-SP0

Traceback (most recent call last):
  File "JWLManager.py", line 1844, in import_items
  File "JWLManager.py", line 1710, in import_notes
  File "pathlib.py", line 871, in __new__
  File "pathlib.py", line 509, in _from_parts
  File "pathlib.py", line 493, in _parse_args
TypeError: expected str, bytes or os.PathLike object, not bool

**Comment by erykjj** [comment]
Hi Glen,

Great catch. I messed up a bit, oops!

Correcting now with v5.1.1. Please confirm.

**Comment by glenmwright** [comment]
That fixed it. You are amazing.

**Comment by erykjj** [comment]
_You_ are amazing for catching these bugs :-)

**Comment by SchneiderSam** [comment]
@erykjj sooo also in the boat 😅 thanks for your amazing work. Excellent wow!! I love the Markdown Export. It works amazing.

My brain is exploding right now. 🤣🤣 Does this mean I can make changes in obsidian/markdown and export back as JWPub? That's ultra cool...

**Comment by SchneiderSam** [comment]
@erykjj And one thing I really miss in JWLibrary are clickable links in the notes (which you can't do anything about, but I'm interested in your approach).

It would be cool, for example:

[An Internal Link to a Bible Verse](/rbi-8/.../chapter/vers)
[This is an external link to jw.org Bible](https://wol.jw.org/de/wol/binav/r10/lp-x)

Have you found a workaround for yourself? I could of course just put it in the note anyway, a link would be created and at least I can see it in Obsidian...

**Comment by SchneiderSam** [comment]
Ok, there a lot of missing links in my JW Notes 😅👋 Thanks again a lot!!!
![image](https://github.com/user-attachments/assets/34f01f4e-00d6-4130-a312-df91d7612da1)

**Comment by erykjj** [comment]
Hi @SchneiderSam 

> Does this mean I can make changes in obsidian/markdown and export back as JWPub?

No, not for now. As I mentioned, you would have to make your own "adapter" to merge all your markdown note files into either an Excel file or into a text file with my "proprietary" import format :-)

However, I will consider adding markdown import in the future.

**Comment by erykjj** [comment]
> @erykjj And one thing I really miss in JWLibrary are clickable links in the notes (which you can't do anything about, but I'm interested in your approach).
> 
> It would be cool, for example:
> 
> `[An Internal Link to a Bible Verse](/rbi-8/.../chapter/vers)` `[This is an external link to jw.org Bible](https://wol.jw.org/de/wol/binav/r10/lp-x)`
> 
> Have you found a workaround for yourself? I could of course just put it in the note anyway, a link would be created and at least I can see it in Obsidian...

No, JW Library doesn't allow any rich text or links in the notes for now. You can still put them in, like you mentioned, it's just that they won't be clickable. I use a lot of * to italicize *Hebrew* or *Greek* words in my notes. They don't display in italics, but just having the * there makes my brain read it so :-)

**Comment by erykjj** [comment]
> there a lot of missing links in my JW Notes

Not sure if that was a... "complaint" (as in, something wrong) or a statement of a fact that you need to correct :-)

**Comment by SchneiderSam** [comment]
> Not sure if that was a... "complaint" (as in, something wrong) or a statement of a fact that you need to correct :-)

a statement of a fact that i need to correct 😅🤣

**Comment by SchneiderSam** [comment]
@erykjj 

> there makes my brain read it so :-)

it would be really cool if Markdown were possible in the JW notes at some point. Of course, it's probably very “unimportant” from a global perspective, but who knows... maybe it will come one day. Until then, I'll follow your example and train my brain... 😉

> However, I will consider adding markdown import in the future.

That would be very cool. Should I open a new issue for an better feature request overview? The export function seems to work wonderfully... Thanks again...
