### ISSUE TITLE
My JWL keeps crashing...

### ISSUE THREAD

**Issue by didpeugeot** [erykjj/jwlmanager#182]
JWLManager v4.5.3
macOS-15.0.1-x86_64-i386-64bit

Traceback (most recent call last):
  File "JWLManager.py", line 1210, in export_items
  File "JWLManager.py", line 1094, in export_notes
TypeError: can only concatenate str (not "NoneType") to str

**Comment by erykjj** [comment]
Thank you for reporting!

Out of curiousity: did you in any way modify the .jwlibrary backup archive, other than with JW Library itself or JWLManager?

**Comment by didpeugeot** [comment]
No change. Straight export from JWL. Open into JWL Manager. I have tried a few times over the course of the last few months: restarted computer, cleared cache, etc. But it always crashes before finishing.

**Comment by erykjj** [comment]
One (or more) of your notes has/have a NULL title field. I have fixed the code to catch this exception.

Are you up to some testing for me?

**Comment by erykjj** [comment]
Please test v[5](https://github.com/erykjj/jwlmanager/releases/tag/v5.0.0)

**Comment by didpeugeot** [comment]
Version 5 worked. All notes into 1 LONG file text! Thank you.
