### ISSUE TITLE
Archive name not visible in dark mode

### ISSUE THREAD

**Issue by SchneiderSam** [erykjj/jwlmanager#187]
Please Check:
<img width="752" alt="image" src="https://github.com/user-attachments/assets/e83bfaa8-9a25-4689-9130-3e5c77f431f3">

In Dark Mode it would be cool if we get a better contrast :-) Thanks ;-)

WIndows 11
![image](https://github.com/user-attachments/assets/92300ba9-f7c7-49bb-b7ea-992de72d0e91)

**Comment by erykjj** [comment]
Hi @SchneiderSam 

Thank you for the suggestion. I have not give any attention to theming at all. I will put that on my todo list ;-)

Any specific suggestions in that direction would be appreciated.

Eryk

**Comment by SchneiderSam** [comment]
> Any specific suggestions in that direction would be appreciated.

White like the other text font is for me totally ok. To be honest: Its not sooo important, just a little tweak. There are other areas that could be much more interesting... :-)

**Comment by erykjj** [comment]
I just noticed your big red arrow pointing at... the invisible text :-))

Yes, the dark mode is handled automatically by the OS, but that particular string isn't. I will have a look.

Good catch!

**Comment by erykjj** [comment]
Fixed. Should be OK in next release.

**Comment by erykjj** [comment]
Out of curiousity: how does the Data Viewer and Data Editor look in dark mode on Windows/Mac?

**Comment by SchneiderSam** [comment]
> Out of curiousity: how does the Data Viewer and Data Editor look in dark mode on Windows/Mac?

you mean this views?
![image](https://github.com/user-attachments/assets/dfb4258f-984e-4d36-83ed-4d6a4b1e8724)
![image](https://github.com/user-attachments/assets/0095ef99-8fbf-4875-8448-cc6c95a33557)

**Comment by erykjj** [comment]
Yes, thank you.

I see I need to fix the icons.

And what do you think of the note colors? Should they be the same as in light mode (yellow, blue, green, etc.), or inverse (dark mode version)?

**Comment by SchneiderSam** [comment]
> And what do you think of the note colors? Should they be the same as in light mode (yellow, blue, green, etc.), or inverse (dark mode version)?

could be inverse but for me its ok. Some inspiration:

JWL note in dark Mode (inverse):
![image](https://github.com/user-attachments/assets/228fdfd3-eecb-41e8-82c0-410db04751da)


JWL note in light mode:
![image](https://github.com/user-attachments/assets/b738fa4a-e3b0-4c88-a167-b0c2f7b3e9f6)
