### ISSUE TITLE
Optional Selection of Properties for Markdown Export

### ISSUE THREAD

**Issue by SchneiderSam** [erykjj/jwlmanager#195]
**Description**:  
Since the latest version of JWL Manager (6.0), it is now possible to export notes in Markdown format with properties automatically linked. This is a very useful feature as it allows users to have various information links embedded directly in the exported notes.

**Problem**:  
However, it has become evident that with a large number of notes, or with particularly extensive notes, this abundance of links can quickly become overwhelming. Tools like Obsidian where the Local Graph is used or when notes are visualized in more detail, can become cluttered with excessive links (also in Logseq, Notion, Bear and so on). For example, general terms like “language” or certain "publications" generate too many links, which hampers clarity in the graph display. And after the test phase, I have to say that the benefits are not that great. A Bible verse is important. Yes, but all the other meta fields are somehow not so useful.

**Suggestion**:  
To enhance clarity, it would be helpful to have an option to select which properties to include as links when exporting Markdown files. Specifically, a pop-up could appear during the export process, allowing users to granularly choose which properties should be linked. This way, users could, for instance, include only certain properties like the document or language, resulting in a more streamlined and customized linking structure.

**Example Workflow**:  
- When starting the export, a pop-up appears listing all available properties (e.g., language, publication, document and color).
- The user can choose which of these properties should be included as links in the export.
- The export then generates _only the selected properties as links_, making the note structure much clearer in Markdown Tools.

**Advantages**:  
- Flexibility in link selection
- Enhanced clarity, especially in graphical displays (e.g., Obsidian Local Graph)
- Allows individual customization to better suit users' needs without excessive linking

**Additional Note**:  
This suggestion originally came from me, and I apologize for "interrupting" now with this additional input. These insights come from feedback I received from friends who reported that the extensive linking feels overwhelming. Personally, I handle it quite well, but I thought it might be beneficial for other users who may share these concerns.

Thank you for considering this suggestion! 😅

**Comment by erykjj** [comment]
No need to apologize, @SchneiderSam. It would be nice if others gave their feedback while the issues are discussed. There is accomplishment through many advisers... :-)

Still, this is a work-in-progress, and the fun part of coding is finding practical solutions to problems.

So, let's start by establishing something. By "linking" in Obsidian, you are referring to the properties that are enclosed in the the [[double brackets]], correct?

If so, currently these are:

- `language`
- `publication`
- `document` (in the case of Bible notes this is the BCV code; for other publications, it's the article document id)
- `color`

So only four, correct? And this seems to cause an overload for some? Or are the tags also being cross-linked? If so, `tag` would also be in the list.

So, which of the four (or five) do we _always_ want included? Any?

**Comment by SchneiderSam** [comment]
Thank you for your questions.

> So only four, correct? And this seems to cause an overload for some?

Correct. I believe the document link is the most important, but everyone should decide for themselves where they need a link and where they don’t. What do you think?

Color is useful, but I need to test it further in real use cases. Links for language and publication aren’t particularly useful. But thats only my oppinion :-)

> Or are the tags also being cross-linked? If so, should tags also be included in the list?

In the Markdown tools I'm familiar with, content starting with a hash is automatically converted to a tag. We had only placed quotation marks around the tags to avoid errors with special characters:  
https://github.com/erykjj/jwlmanager/issues/194#issuecomment-2466274460

So, I think it's important that they continue to have the quotation marks as they do now. No changes are needed for tags at the moment.

> So, which of the four (or five) do we always want included? Any?

**Always:**

Tags (due to the bug we found here: https://github.com/erykjj/jwlmanager/issues/194#issuecomment-2466274460)

**Optional:**
- Document
- Language
- Publication
- Color

**Comment by erykjj** [comment]
I think we're talking about differente things :-)

I mean, the cross-linking is related to the [[ ]] (not the ""). Are tags also cross-linked (automatically)? Because tags are not in [[ ]]. Do we _always_ include the tags?

So, document -  always; tags - always; color - sometimes; language - sometimes. About right?

Publication? Useful at all? Sometimes or never?

**Comment by SchneiderSam** [comment]
Thanks for the clarifications!

Yes, you're correct – tags have a different function than links in `[[ ]]`. It’s really important that tags remain in the export as they play a key role in maintaining structure and functionality. So, if a JWL note has a tag, that tag should also appear in the exported md-note to keep everything consistent between JWL and the export.

Regarding which properties should always be linked, I’m not entirely certain, as preferences on this may vary. Personally, I find the `document` link to be the most essential, but other users might prioritize different properties. It would probably be best for everyone if each user could decide which properties are most important to them and which ones are less relevant.

So, my recommendation would be to have a selection option for all properties at export, allowing users to mark links as needed. This way, everyone can choose the links that are most useful to them.

I hope this answers your questions – if not, just let me know!

Thanks again for your support! 😊

**Comment by erykjj** [comment]
Proposal:
- `document` will always be in [[ ]] (linked)
- `tags` (if present) will always be listed
- `publication` will be a simple string (not linked)
- if selected `Grouping` drop-down is "Language", then `language` would be linked via [[ ]] as well (otherwise, just a simple string - no double-brackets)
- if selected `Grouping` drop-down is "Color", then `color` would be linked via [[ ]] as well (otherwise, just a simple string - no double-brackets)

Would that serve? 

@SchneiderSam , please request feedback from your friends ;-)

**Comment by SchneiderSam** [comment]
> Would that serve?

that would be very very good. THANKS :-)

**Comment by SchneiderSam** [comment]
> Proposal:
> 
> * `document` will always be in [[ ]] (linked)
> * `tags` (if present) will always be listed
> * `publication` will be a simple string (not linked)
> * if selected `Grouping` drop-down is "Language", then `language` would be linked via [[ ]] as well (otherwise, just a simple string - no double-brackets)
> * if selected `Grouping` drop-down is "Color", then `color` would be linked via [[ ]] as well (otherwise, just a simple string - no double-brackets)
> 
> Would that serve?

@rgeyer67 what do you think?

**Comment by erykjj** [comment]
> * `document` will always be in [[ ]] (linked)
> 
> * `tags` (if present) will always be listed
> 
> * `publication` will be a simple string (not linked)
> 
> * if selected `Grouping` drop-down is "Language", then `language` would be linked via [[ ]] as well (otherwise, just a simple string - no double-brackets)
> 
> * if selected `Grouping` drop-down is "Color", then `color` would be linked via [[ ]] as well (otherwise, just a simple string - no double-brackets)

Implemented in [v6.1.0](https://github.com/erykjj/jwlmanager/releases/tag/v6.1.0)
