### ISSUE TITLE
JW Library app structured  links in exported notes

### ISSUE THREAD

**Issue by riggles** [erykjj/jwlmanager#196]
I just discovered this project and am quite excited to work with it! Especially seeing if I can integrate with my Markdown notes.

One thing I noticed from the exported NWT notes is the URL in the `link` property goes to the online Bible on jw.org. Everyone has their own workflow, of course, so this may be exactly what some are looking for. I like using links that go right to the JW Library app, though, as it requires no internet connection and is where I typically want to read scriptures from anyway. These links are generated from JWL on iOS/iPadOS via **Share Menu > Copy**. The URL structure is a bit different, though. For example, a link to Isaiah 40:29:

Exported note: `https://www.jw.org/finder?wtlocale=0&pub=nwtsty&bible=23040029`
Shared note: `https://www.jw.org/finder?srcid=jwlshare&wtlocale=E&prefer=lang&bible=23040029&pub=nwtsty`

The changes are the addition of `srcid` and `prefer` queries, the order of `pub` in the string, and the value of `wtlocale` changing from integer to character.

Would having the option for JWL app structured links be something you see a value in adding? Granted I don't know if this link structure is unique to each OS, which would for sure make it more challenging. Thank you for your thoughts and this great tool.

**Comment by erykjj** [comment]
Hi @riggles !

Thank you for your suggestion. I will have a look and see what we can do ;-)

**Comment by erykjj** [comment]
@riggles , can you test the Python script directly or would you need a compiled version for the Mac or Windows?

**Comment by erykjj** [comment]
> the value of `wtlocale` changing from integer to character.

You actually found a bug :-) It should be the letter code. I have fixed it and it should work correctly now.

But I may wait a bit to resolve another issue (at least partially).

**Comment by riggles** [comment]
> @riggles , can you test the Python script directly or would you need a compiled version for the Mac or Windows?

I'm no developer, but if you tell me what's needed, I'm somewhat comfortable running something in Terminal on my Mac.

**Comment by erykjj** [comment]
No worries.

Just as a quick test, just change the `wtlocale=0` to `wtlocale=E` in the link in any of your exported markdown files and see if it opens up in JW Library.

**Comment by riggles** [comment]
> No worries.
> 
> Just as a quick test, just change the `wtlocale=0` to `wtlocale=E` in the link in any of your exported markdown files and see if it opens up in JW Library.

Wow, that was it! Changed that one thing, and the link opened in JW Library. Excellent.

**Comment by erykjj** [comment]
Fixed in [v6.1.0](https://github.com/erykjj/jwlmanager/releases/tag/v6.1.0)
