### ISSUE TITLE
Export feature

### ISSUE THREAD

**Issue by Chiriat** [erykjj/jwlmanager#197]
Hi Erykjj
Thanks for the software. It is very useful.

Just a suggestion... Is it possible to export notes choosing a specific tag?  

Thanks

**Comment by erykjj** [comment]
Hi @Chiriat 

Yes, in the **Grouping** drop-down, select "Tag", and then only select the tag(s) you want to export

**Comment by Chiarit1** [comment]
Thanks,
The problem is when that tag is not the first in the tag list. For example the records have the following tags:
Noah | Flood | Obedience
Obedience | David

If I wanted to extract all the records where '"obedience" occurs, how can I do it?

**Comment by erykjj** [comment]
Hi @Chiarit1 
You simply select all the lines where you see your tag ("Obedience"), that's all. In your example, select both.

**Comment by Chiarit1** [comment]
OK, Thanks, will do.
It just take a lot of time to select them, if i have a long list. 

![image](https://github.com/user-attachments/assets/033c689b-b405-415f-9b24-58f7a1d92fc2)

**Comment by erykjj** [comment]
You could export everything to Excel, then use the filter function in the tag column...
