### ISSUE TITLE
Overwriting and adding highlights from two different backups

### ISSUE THREAD

**Issue by xKamil01** [erykjj/jwlmanager#198]
Hey, I have a problem, when I export underlines from one backup (26,000) and later I want to import to a new backup (28,700) it changes to about 26,000 "underlines". I checked and there are no newest underlines, so overwriting and adding does not work.

Polish and English language, latest version

**Comment by xKamil01** [comment]
Indeed, everything works fine. I'm a bit confused and I used an outdated backup. Everything works, thank you.

But I have another problem/suggestion to change:

When exporting playlists, they are somehow merged together.
![Screenshot_1978](https://github.com/user-attachments/assets/b2c27818-afb8-4a2b-b286-c93a3af850f1)

When importing, the entire playlist is one. It would be nice if the program separated them, or created a separate .jwplaylist file for each when exporting all playlists
![Screenshot_1979](https://github.com/user-attachments/assets/a3d2974f-520c-4157-a1a0-f5b855d19c3b)

**Comment by erykjj** [comment]
The playlist export/import works as intended. The idea is to select images from your playlist collection and export them into one - for a talk, for instance. If you want separate, simply export them separately.

The filename (of the .jwlplaylist file) defines the name of the exported playlist. So, if you want your exported items to become part of a playlist called "Bible", export them to "Bible.jwlplaylist" and then import them into your archive.

If you import a .jwlibrary archive through the playlist import, all the playlists it contain will be imported as is.
