### ISSUE TITLE
Crash When Viewing Annotations in JWLManager v6.1.1

### ISSUE THREAD

**Issue by opathofer** [erykjj/jwlmanager#199]
# Bug Report: Crash When Viewing Annotations in JWLManager v6.1.1

## Environment
- **JWLManager Version**: 6.1.1  
- **Operating System**: Windows 10 (Build 10.0.22621-SP0)  
- **JW Library Version**: Latest  

## Steps to Reproduce
1. Open the most recent JW Library backup file (`File -> Open`).  
2. Navigate to the **Annotations** category (I have a total of 165 annotations).  
3. Select any publication and click **View**.  

### Result
The following error message appears:  

```
Oops! Something went wrong...

JWLManager v6.1.1
Windows-10-10.0.22621-SP0

Traceback (most recent call last):
  File "JWLManager.py", line 2367, in data_viewer
  File "JWLManager.py", line 2303, in show_annotations
  File "res\ui_extras.py", line 355, in __init__
    self.text_box.setProperty('note', colors[color])
                                      ~~~~~~^^^^^^^
KeyError: '#f1f1f1'
```

### Observations
- Export functionality for annotations works as expected.  

## Additional Information
- I can provide the `.jwlibrary` file for further debugging upon request. Please let me know where to send it.  

Thank you for your assistance!

**Comment by erykjj** [comment]
First of all, @opathofer, thank you for submitting such a great bug report! Much appreciated ;-)

The issue was a left-over from the theme-switching I added. It should be fixed in [v6.1.2](https://github.com/erykjj/jwlmanager/releases/tag/v6.1.2). Please test and confirm. Thank you again!
