### ISSUE TITLE
Jwpub 

### ISSUE THREAD

**Issue by Reulym** [erykjj/jwlmanager#77]
hello. I saw the jwpub that did. excellent job. I have some projects in jwpub and I would like to share with you and exchange experiences. I'm not a professional programmer but I really like the area and I study the subject in my spare time. I am from a congregation in Brazil. If you can contact me this is my email: ifontelescosta@gmail.com

**Comment by erykjj** [comment]
Hi @Reulym ,
You are welcome to share your observations/suggestions regarding the content or layout of the resources that I share here, but as indicated in the README, I will not discuss the production/creation methods. Thank you for your understanding.
