### ISSUE TITLE
Export of 980 Study bible notes caused the app to crash

### ISSUE THREAD

**Issue by dl9abl** [erykjj/jwlmanager#90]
JWLManager v2.3.2

Traceback (most recent call last):
  File "JWLManager.py", line 1198, in __init__
  File "JWLManager.py", line 1210, in export_items
  File "JWLManager.py", line 1216, in export_notes
  File "JWLManager.py", line 1239, in export_bible
sqlite3.OperationalError: no such column: n.Created

**Comment by erykjj** [comment]
Hi Roland,

Thank you for reporting. I believe the .jwlibrary archive you're working with was created by an older version of JW Library (<14), correct?

I updated my app to work with the newer (14+) version, but will need to push a fix for it to handle the olders archives correctly.

**Comment by dl9abl** [comment]
Hello Erik!

 

Thanks for your reply. Sorry, you are right. Everything works well.

 

Have a great weekend - Roland

 

Von: Eryk J. ***@***.***> 
Gesendet: Freitag, 18. August 2023 15:45
An: erykjj/jwlmanager ***@***.***>
Cc: Roland ***@***.***>; Author ***@***.***>
Betreff: Re: [erykjj/jwlmanager] Export of 980 Study bible notes caused the app to crash (Issue #90)

 

Hi Roland,

Thank you for reporting. I believe the .jwlibrary archive you're working with was created by an older version of JW Library (<14), correct?

I updated my app to work with the newer (14+) version, but will need to push a fix for it to handle the olders archives correctly.

**Comment by erykjj** [comment]
Temporary fix via d1ae8f1b61c0b92b56939ebbee0b2aada336bc29
